apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - image: appnetorg/echo-symphony:latest
        name: frontend-echo-symphony
        command: ["/app/frontend/frontend"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      - image: appnetorg/symphony-proxy:latest
        name: symphony-proxy
        command: ["/app/proxy"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
          runAsUser: 1337
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  clusterIP: None
  ports:
  - name: server
    port: 9000
    protocol: UDP
    targetPort: 9000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
      - image: appnetorg/echo-symphony:latest
        name: server-echo-symphony
        command: ["/app/server/server"]
  selector:
    matchLabels:
      app: server