apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: frontend
    image: appnetorg/echo-symphony:latest
    command: ["/app/frontend/frontend"]
    ports:
    - containerPort: 8080
  - name: symphony-proxy
    image: appnetorg/symphony-proxy:latest
    command: ["/app/proxy"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]
      runAsUser: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  clusterIP: None
  ports:
  - name: server
    port: 9000
    protocol: UDP
    targetPort: 9000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
      - image: appnetorg/echo-symphony:latest
        name: server-echo-symphony
        command: ["/app/server/server"]
  selector:
    matchLabels:
      app: server